apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeskoop-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    debugmode: {{ .Values.agent.config.debug }}
    port: {{ .Values.agent.config.port }}
    enableController: {{ .Values.controller.enabled }}
    metrics:
      additionalLabels:
      {{- toYaml .Values.config.additionalLabels | nindent 8 }}
      probes:
      {{- toYaml .Values.config.metricProbes | nindent 6 }}
    event:
      probes:
      {{- toYaml .Values.config.eventProbes | nindent 6 }}
      sinks:
      {{- toYaml .Values.config.eventSinks | nindent 6 }}
