// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package tracesocketlatency

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfInspSklatEventT struct {
	Target [20]int8
	Tuple  struct {
		Saddr   struct{ V6addr [16]uint8 }
		Daddr   struct{ V6addr [16]uint8 }
		Sport   uint16
		Dport   uint16
		L3Proto uint16
		L4Proto uint8
		Pad     uint8
	}
	SkbMeta struct {
		Netns    uint32
		Mark     uint32
		Ifindex  uint32
		Len      uint32
		Mtu      uint32
		SkState  uint32
		Protocol uint16
		Pad      uint16
	}
	Pid       uint32
	Cpu       uint32
	Direction uint32
	_         [4]byte
	Latency   uint64
}

type bpfInspSklatMetricT struct {
	Netns  uint32
	Pid    uint32
	Cpu    uint32
	Bucket uint32
	Action uint32
}

type bpfSklatKeyT struct {
	Createat    uint64
	Lastreceive uint64
	Lastread    uint64
	Lastwrite   uint64
	Lastsend    uint64
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	SockCreate  *ebpf.ProgramSpec `ebpf:"sock_create"`
	SockDestroy *ebpf.ProgramSpec `ebpf:"sock_destroy"`
	SockRead    *ebpf.ProgramSpec `ebpf:"sock_read"`
	SockReceive *ebpf.ProgramSpec `ebpf:"sock_receive"`
	SockSend    *ebpf.ProgramSpec `ebpf:"sock_send"`
	SockWrite   *ebpf.ProgramSpec `ebpf:"sock_write"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	InspSklatEntry  *ebpf.MapSpec `ebpf:"insp_sklat_entry"`
	InspSklatEvents *ebpf.MapSpec `ebpf:"insp_sklat_events"`
	InspSklatMetric *ebpf.MapSpec `ebpf:"insp_sklat_metric"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	InspSklatEntry  *ebpf.Map `ebpf:"insp_sklat_entry"`
	InspSklatEvents *ebpf.Map `ebpf:"insp_sklat_events"`
	InspSklatMetric *ebpf.Map `ebpf:"insp_sklat_metric"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.InspSklatEntry,
		m.InspSklatEvents,
		m.InspSklatMetric,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	SockCreate  *ebpf.Program `ebpf:"sock_create"`
	SockDestroy *ebpf.Program `ebpf:"sock_destroy"`
	SockRead    *ebpf.Program `ebpf:"sock_read"`
	SockReceive *ebpf.Program `ebpf:"sock_receive"`
	SockSend    *ebpf.Program `ebpf:"sock_send"`
	SockWrite   *ebpf.Program `ebpf:"sock_write"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.SockCreate,
		p.SockDestroy,
		p.SockRead,
		p.SockReceive,
		p.SockSend,
		p.SockWrite,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel_x86.o
var _BpfBytes []byte
