// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package tracevirtcmdlat

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfInspVirtcmdlatEventT struct {
	Pid     uint32
	Cpu     uint32
	Latency uint64
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TraceVirtcmd    *ebpf.ProgramSpec `ebpf:"trace_virtcmd"`
	TraceVirtcmdret *ebpf.ProgramSpec `ebpf:"trace_virtcmdret"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	InspVirtcmdlat       *ebpf.MapSpec `ebpf:"insp_virtcmdlat"`
	InspVirtcmdlatEvents *ebpf.MapSpec `ebpf:"insp_virtcmdlat_events"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	InspVirtcmdlat       *ebpf.Map `ebpf:"insp_virtcmdlat"`
	InspVirtcmdlatEvents *ebpf.Map `ebpf:"insp_virtcmdlat_events"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.InspVirtcmdlat,
		m.InspVirtcmdlatEvents,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TraceVirtcmd    *ebpf.Program `ebpf:"trace_virtcmd"`
	TraceVirtcmdret *ebpf.Program `ebpf:"trace_virtcmdret"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TraceVirtcmd,
		p.TraceVirtcmdret,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel_x86.o
var _BpfBytes []byte
