{
 "title": "skoop-exporter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "pod", "label": "pod", "query": { "query": "label_values(pod)" } },
   { "name": "node", "label": "Node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  { "title": "Network Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Socket Memory Usage Kernel+User (page)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "page/s" } },
   "targets": [
    {
     "expr": "sum(kubeskoop_sock_mem{k8s_node=\"$node\"}) by (node)",
     "legendFormat": "{{k8s_node}}"
    }
   ]
  },
  {
   "title": "Packet abnormal loss(times）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(kubeskoop_packetloss_total{k8s_node=\"$node\"}[2m])) by (k8s_node)",
     "legendFormat": "{{k8s_node}}"
    }
   ]
  },
  {
   "title": "Network Device RX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_netdev_rxbytes{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "Socket Allocate count(include orphan）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kubeskoop_sock_alloc{k8s_node=\"$node\"}) by (node)",
     "legendFormat": "{{k8s_node}}"
    }
   ]
  },
  {
   "title": "Network Device TX errors(times)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_netdev_txerrors[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "Network Device TX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(kubeskoop_netdev_txbytes{k8s_pod=\"$pod\"}[2m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "Netdev RX/TX Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_netdev_rxpackets[2m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    },
    {
     "expr": "rate(kubeskoop_netdev_txpackets[2m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "Network Device RX errors(times)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_netdev_rxerrors[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  { "title": "Risk Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "RetranSegs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(kubeskoop_tcp_retranssegs{k8s_node=\"$node\"}[1m])) by (node)",
     "legendFormat": "{{k8s_node}}"
    },
    {
     "expr": "rate(kubeskoop_tcp_retranssegs{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "{{k8s_pod}}"
    }
   ]
  },
  {
   "title": "TCP Established Conn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(kubeskoop_tcpsummary_tcpestablishedconn{k8s_node=\"$node\"}) by (node)",
     "legendFormat": "{{k8s_node}}"
    },
    {
     "expr": "kubeskoop_tcpsummary_tcpestablishedconn{k8s_pod=\"$pod\"}",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "TCP RTO-Timeout times",
   "type": "timeseries",
   "description": "由本地发起的连接出现连接失败是也会造成RTO超时增加",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "increase(kubeskoop_tcpext_tcptimeouts{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "TCP Timewait Conn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "kubeskoop_tcpsummary_tcptimewaitconn{k8s_pod=\"$pod\"}",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "TCP Listen Backlog overflow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_tcpext_listenoverflows{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "TCP handshake drop(listendrop)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_tcpext_listendrops{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  { "title": "Unexpected Delay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Socket Read Latency( > 100ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_socketlatency_read100ms{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "{{k8s_node}}"
    }
   ]
  },
  {
   "title": "Socket Wqueue remain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubeskoop_tcpsummary_tcptxqueue{k8s_pod=\"$pod\"}",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "Socket Rqueue remain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubeskoop_tcpsummary_tcprxqueue{k8s_pod=\"$pod\"}",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "Kernel Latency (tx && rx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_kernellatency_rxslow{}[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    },
    {
     "expr": "rate(kubeskoop_kernellatency_txslow{}[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "Net Softirq sched slow(more than 10ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_softirq_schedslow{k8s_node=\"$node\"}[1m]) ",
     "legendFormat": "{{softirq_type}}"
    }
   ]
  },
  {
   "title": "Network softirq Sched more than 100ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_softirq_schedslow100ms{k8s_node=\"$node\"}[1m])",
     "legendFormat": "{{softirq_type}}"
    }
   ]
  },
  {
   "title": "Net Softirq execute slow(more than 10ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_softirq_excuteslow{k8s_node=\"$node\"}[1m]) ",
     "legendFormat": "{{softirq_type}}"
    }
   ]
  },
  {
   "title": "Net Softirq execute slow(more than 100ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_softirq_excuteslow100ms{k8s_node=\"$node\"}[1m]) ",
     "legendFormat": "{{softirq_type}}"
    }
   ]
  },
  {
   "title": "Virtio command execute low",
   "type": "timeseries",
   "description": "在偶发延迟场景中，需要关注是否出现这个指标的增长。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "kubeskoop_virtcmdlatency_latency{k8s_node=\"$node\"}",
     "legendFormat": "{{k8s_node}}/le {{le}}"
    }
   ]
  },
  {
   "title": "IO Read rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_io_readbytes{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "IO Write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_io_writebytes{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "IO Syscall times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_io_writesyscall{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "W-{{k8s_pod}}/{{k8s_node}}"
    },
    {
     "expr": "rate(kubeskoop_io_readsyscall{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "R-{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  { "title": "DNS/UDP Timeout", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "UDP RX rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_udp_indatagrams{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "UDP TX rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_udp_outdatagrams{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "UDP RCV-Buffer exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "kubeskoop_udp_rcvbuferrors{k8s_pod=\"$pod\"}",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "UDP SND-Buffer exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_udp_sndbuferrors{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "UDP No-Ports",
   "type": "timeseries",
   "description": "如果出现dns超时，您需要关注这个指标，通常在Serever返回较慢的情况，例如公网DNS场景，回包慢于用户设定超时，会出现这个情况。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_udp_noports{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "UDP In Error",
   "type": "timeseries",
   "description": "在dns超时场景中，如果查询结果的udp在validate中被丢弃，由于没有重传机制，因此会直接导致超时。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_udp_inerrors{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  { "title": "TCP Abnormal Reset", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "TCP Send RST of memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "kubeskoop_tcpext_tcpabortonmemory{k8s_pod=\"$pod\"}",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "TCP Send RST of keepalive time exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_tcpext_tcpabortontimeout{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "TCP Send RST of SO_LINGER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "times" } },
   "targets": [
    {
     "expr": "kubeskoop_tcpext_tcpabortonlinger{k8s_pod=\"$pod\"}",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  },
  {
   "title": "TCP Send RST of close when data unread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kubeskoop_tcpext_tcpabortonclose{k8s_pod=\"$pod\"}[1m])",
     "legendFormat": "{{k8s_pod}}/{{k8s_node}}"
    }
   ]
  }
 ]
}